# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FichaAmbulatorial.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FichaAmbulatorial(object):
    def setupUi(self, FichaAmbulatorial):
        FichaAmbulatorial.setObjectName("FichaAmbulatorial")
        FichaAmbulatorial.setEnabled(True)
        FichaAmbulatorial.resize(671, 997)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        FichaAmbulatorial.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Desktop/logoHospital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FichaAmbulatorial.setWindowIcon(icon)
        FichaAmbulatorial.setToolTipDuration(-1)
        FichaAmbulatorial.setAutoFillBackground(False)
        FichaAmbulatorial.setStyleSheet("background-color: rgb(192, 255, 218);")
        FichaAmbulatorial.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(FichaAmbulatorial)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetCabecalho = QtWidgets.QWidget(self.centralwidget)
        self.widgetCabecalho.setGeometry(QtCore.QRect(10, 0, 641, 81))
        self.widgetCabecalho.setObjectName("widgetCabecalho")
        self.line_2 = QtWidgets.QFrame(self.widgetCabecalho)
        self.line_2.setGeometry(QtCore.QRect(120, 60, 441, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelTitulo = QtWidgets.QLabel(self.widgetCabecalho)
        self.labelTitulo.setGeometry(QtCore.QRect(120, 20, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelSubTitulo = QtWidgets.QLabel(self.widgetCabecalho)
        self.labelSubTitulo.setGeometry(QtCore.QRect(140, 40, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.labelSubTitulo.setFont(font)
        self.labelSubTitulo.setObjectName("labelSubTitulo")
        self.labelLogo = QtWidgets.QLabel(self.widgetCabecalho)
        self.labelLogo.setGeometry(QtCore.QRect(20, 0, 91, 71))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("Formularios/logoHospital.png"))
        self.labelLogo.setObjectName("labelLogo")
        self.widgetRecepcao = QtWidgets.QWidget(self.centralwidget)
        self.widgetRecepcao.setGeometry(QtCore.QRect(10, 80, 641, 221))
        self.widgetRecepcao.setObjectName("widgetRecepcao")
        self.lineEditTelefone2 = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditTelefone2.setGeometry(QtCore.QRect(520, 180, 121, 20))
        self.lineEditTelefone2.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditTelefone2.setObjectName("lineEditTelefone2")
        self.dateEditNasc = QtWidgets.QDateEdit(self.widgetRecepcao)
        self.dateEditNasc.setGeometry(QtCore.QRect(80, 80, 71, 22))
        self.dateEditNasc.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.dateEditNasc.setObjectName("dateEditNasc")
        self.lineEditBairro = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditBairro.setGeometry(QtCore.QRect(430, 150, 71, 20))
        self.lineEditBairro.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditBairro.setObjectName("lineEditBairro")
        self.lineEditSexo = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditSexo.setGeometry(QtCore.QRect(450, 50, 71, 20))
        self.lineEditSexo.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditSexo.setObjectName("lineEditSexo")
        self.labelCorRaca = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelCorRaca.setGeometry(QtCore.QRect(520, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelCorRaca.setFont(font)
        self.labelCorRaca.setObjectName("labelCorRaca")
        self.lineEditTelefone1 = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditTelefone1.setGeometry(QtCore.QRect(520, 110, 121, 20))
        self.lineEditTelefone1.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditTelefone1.setObjectName("lineEditTelefone1")
        self.labelNomeMae = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelNomeMae.setGeometry(QtCore.QRect(0, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelNomeMae.setFont(font)
        self.labelNomeMae.setObjectName("labelNomeMae")
        self.labelTelefone2 = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelTelefone2.setGeometry(QtCore.QRect(490, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelTelefone2.setFont(font)
        self.labelTelefone2.setObjectName("labelTelefone2")
        self.labelAssinatura = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelAssinatura.setGeometry(QtCore.QRect(0, 180, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelAssinatura.setFont(font)
        self.labelAssinatura.setObjectName("labelAssinatura")
        self.labelCidade = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelCidade.setGeometry(QtCore.QRect(510, 150, 47, 13))
        self.labelCidade.setObjectName("labelCidade")
        self.label_3 = QtWidgets.QLabel(self.widgetRecepcao)
        self.label_3.setGeometry(QtCore.QRect(0, 150, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditLongradouro = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditLongradouro.setGeometry(QtCore.QRect(70, 150, 231, 20))
        self.lineEditLongradouro.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditLongradouro.setObjectName("lineEditLongradouro")
        self.labelBairro = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelBairro.setGeometry(QtCore.QRect(380, 150, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelBairro.setFont(font)
        self.labelBairro.setObjectName("labelBairro")
        self.lineEditCorRaca = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditCorRaca.setGeometry(QtCore.QRect(580, 80, 61, 20))
        self.lineEditCorRaca.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditCorRaca.setObjectName("lineEditCorRaca")
        self.lineEditIdade = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditIdade.setGeometry(QtCore.QRect(580, 50, 61, 20))
        self.lineEditIdade.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditIdade.setObjectName("lineEditIdade")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widgetRecepcao)
        self.radioButton_3.setGeometry(QtCore.QRect(390, 20, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.labelNome = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelNome.setGeometry(QtCore.QRect(0, 50, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelNome.setFont(font)
        self.labelNome.setObjectName("labelNome")
        self.lineEditNome = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditNome.setGeometry(QtCore.QRect(50, 50, 341, 20))
        self.lineEditNome.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditNome.setText("")
        self.lineEditNome.setObjectName("lineEditNome")
        self.lineEditCns = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditCns.setGeometry(QtCore.QRect(320, 80, 191, 20))
        self.lineEditCns.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditCns.setObjectName("lineEditCns")
        self.labelDataNasc = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelDataNasc.setGeometry(QtCore.QRect(0, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelDataNasc.setFont(font)
        self.labelDataNasc.setObjectName("labelDataNasc")
        self.lineEditNomeMae = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditNomeMae.setGeometry(QtCore.QRect(100, 110, 341, 20))
        self.lineEditNomeMae.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditNomeMae.setObjectName("lineEditNomeMae")
        self.radioButton = QtWidgets.QRadioButton(self.widgetRecepcao)
        self.radioButton.setGeometry(QtCore.QRect(240, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.lineEditNumero = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditNumero.setGeometry(QtCore.QRect(340, 150, 31, 20))
        self.lineEditNumero.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditNumero.setObjectName("lineEditNumero")
        self.label = QtWidgets.QLabel(self.widgetRecepcao)
        self.label.setGeometry(QtCore.QRect(130, 20, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelTema = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelTema.setGeometry(QtCore.QRect(200, 0, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTema.setFont(font)
        self.labelTema.setObjectName("labelTema")
        self.lineAssinaturaResponsavel = QtWidgets.QFrame(self.widgetRecepcao)
        self.lineAssinaturaResponsavel.setGeometry(QtCore.QRect(170, 190, 321, 16))
        self.lineAssinaturaResponsavel.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineAssinaturaResponsavel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineAssinaturaResponsavel.setObjectName("lineAssinaturaResponsavel")
        self.line_3 = QtWidgets.QFrame(self.widgetRecepcao)
        self.line_3.setGeometry(QtCore.QRect(0, 200, 651, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.labelNumero = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelNumero.setGeometry(QtCore.QRect(310, 150, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelNumero.setFont(font)
        self.labelNumero.setObjectName("labelNumero")
        self.labelData = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelData.setGeometry(QtCore.QRect(0, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.timeEditHoraChegada = QtWidgets.QTimeEdit(self.widgetRecepcao)
        self.timeEditHoraChegada.setGeometry(QtCore.QRect(180, 20, 51, 22))
        self.timeEditHoraChegada.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.timeEditHoraChegada.setObjectName("timeEditHoraChegada")
        self.labelIdade = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelIdade.setGeometry(QtCore.QRect(530, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelIdade.setFont(font)
        self.labelIdade.setObjectName("labelIdade")
        self.dateEditHoje = QtWidgets.QDateEdit(self.widgetRecepcao)
        self.dateEditHoje.setGeometry(QtCore.QRect(40, 20, 81, 22))
        self.dateEditHoje.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.dateEditHoje.setObjectName("dateEditHoje")
        self.lineEdit = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEdit.setGeometry(QtCore.QRect(550, 150, 91, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEdit.setObjectName("lineEdit")
        self.labelTelefone1 = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelTelefone1.setGeometry(QtCore.QRect(480, 110, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelTelefone1.setFont(font)
        self.labelTelefone1.setObjectName("labelTelefone1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widgetRecepcao)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 20, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.labelSexo = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelSexo.setGeometry(QtCore.QRect(400, 50, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelSexo.setFont(font)
        self.labelSexo.setObjectName("labelSexo")
        self.lineEditConvenio = QtWidgets.QLineEdit(self.widgetRecepcao)
        self.lineEditConvenio.setGeometry(QtCore.QRect(480, 20, 161, 20))
        self.lineEditConvenio.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditConvenio.setObjectName("lineEditConvenio")
        self.labelCns = QtWidgets.QLabel(self.widgetRecepcao)
        self.labelCns.setGeometry(QtCore.QRect(160, 80, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelCns.setFont(font)
        self.labelCns.setObjectName("labelCns")
        self.widgetMedico = QtWidgets.QWidget(self.centralwidget)
        self.widgetMedico.setGeometry(QtCore.QRect(10, 300, 641, 301))
        self.widgetMedico.setObjectName("widgetMedico")
        self.lineAssinaturaMedico = QtWidgets.QFrame(self.widgetMedico)
        self.lineAssinaturaMedico.setGeometry(QtCore.QRect(280, 290, 361, 16))
        self.lineAssinaturaMedico.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineAssinaturaMedico.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineAssinaturaMedico.setObjectName("lineAssinaturaMedico")
        self.labelDiagnsticoMedico = QtWidgets.QLabel(self.widgetMedico)
        self.labelDiagnsticoMedico.setGeometry(QtCore.QRect(0, 20, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelDiagnsticoMedico.setFont(font)
        self.labelDiagnsticoMedico.setObjectName("labelDiagnsticoMedico")
        self.textEditDescricao = QtWidgets.QTextEdit(self.widgetMedico)
        self.textEditDescricao.setGeometry(QtCore.QRect(0, 40, 641, 91))
        self.textEditDescricao.setStyleSheet("background-color: rgb(255, 249, 248);")
        self.textEditDescricao.setObjectName("textEditDescricao")
        self.labelProcedimentoMedico = QtWidgets.QLabel(self.widgetMedico)
        self.labelProcedimentoMedico.setGeometry(QtCore.QRect(0, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelProcedimentoMedico.setFont(font)
        self.labelProcedimentoMedico.setObjectName("labelProcedimentoMedico")
        self.textEditDescricaoMedico = QtWidgets.QTextEdit(self.widgetMedico)
        self.textEditDescricaoMedico.setGeometry(QtCore.QRect(0, 160, 641, 111))
        self.textEditDescricaoMedico.setStyleSheet("background-color: rgb(255, 249, 248);")
        self.textEditDescricaoMedico.setObjectName("textEditDescricaoMedico")
        self.labelTema_2 = QtWidgets.QLabel(self.widgetMedico)
        self.labelTema_2.setGeometry(QtCore.QRect(200, 0, 291, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTema_2.setFont(font)
        self.labelTema_2.setObjectName("labelTema_2")
        self.labelIdentificascaoMedico = QtWidgets.QLabel(self.widgetMedico)
        self.labelIdentificascaoMedico.setGeometry(QtCore.QRect(0, 280, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelIdentificascaoMedico.setFont(font)
        self.labelIdentificascaoMedico.setObjectName("labelIdentificascaoMedico")
        self.widgetEnfermagem = QtWidgets.QWidget(self.centralwidget)
        self.widgetEnfermagem.setGeometry(QtCore.QRect(10, 600, 641, 391))
        self.widgetEnfermagem.setObjectName("widgetEnfermagem")
        self.labelObsMedicaNaUnidade = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelObsMedicaNaUnidade.setGeometry(QtCore.QRect(0, 310, 541, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.labelObsMedicaNaUnidade.setFont(font)
        self.labelObsMedicaNaUnidade.setObjectName("labelObsMedicaNaUnidade")
        self.lineEditHoraObsIni_2 = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraObsIni_2.setGeometry(QtCore.QRect(290, 340, 61, 20))
        self.lineEditHoraObsIni_2.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraObsIni_2.setObjectName("lineEditHoraObsIni_2")
        self.radioButtonIntercorrenciaNeg_2 = QtWidgets.QRadioButton(self.widgetEnfermagem)
        self.radioButtonIntercorrenciaNeg_2.setGeometry(QtCore.QRect(540, 370, 41, 17))
        self.radioButtonIntercorrenciaNeg_2.setObjectName("radioButtonIntercorrenciaNeg_2")
        self.labelFR = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelFR.setGeometry(QtCore.QRect(270, 0, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelFR.setFont(font)
        self.labelFR.setObjectName("labelFR")
        self.textEditDescricaoMaterialUtilizado = QtWidgets.QTextEdit(self.widgetEnfermagem)
        self.textEditDescricaoMaterialUtilizado.setGeometry(QtCore.QRect(0, 190, 641, 111))
        self.textEditDescricaoMaterialUtilizado.setStyleSheet("background-color: rgb(255, 249, 248);")
        self.textEditDescricaoMaterialUtilizado.setObjectName("textEditDescricaoMaterialUtilizado")
        self.lineEditHoraLiberacaoSusFacil = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraLiberacaoSusFacil.setGeometry(QtCore.QRect(120, 370, 61, 20))
        self.lineEditHoraLiberacaoSusFacil.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraLiberacaoSusFacil.setObjectName("lineEditHoraLiberacaoSusFacil")
        self.lineEditOxiLPorMin = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditOxiLPorMin.setGeometry(QtCore.QRect(560, 150, 81, 20))
        self.lineEditOxiLPorMin.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditOxiLPorMin.setObjectName("lineEditOxiLPorMin")
        self.lineEditHoraObsFim = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraObsFim.setGeometry(QtCore.QRect(580, 310, 61, 20))
        self.lineEditHoraObsFim.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraObsFim.setObjectName("lineEditHoraObsFim")
        self.lineEditHoraFimOxi = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraFimOxi.setGeometry(QtCore.QRect(420, 150, 51, 20))
        self.lineEditHoraFimOxi.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraFimOxi.setObjectName("lineEditHoraFimOxi")
        self.lineEditHospitalDestinoSusFacil = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHospitalDestinoSusFacil.setGeometry(QtCore.QRect(250, 370, 151, 20))
        self.lineEditHospitalDestinoSusFacil.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHospitalDestinoSusFacil.setObjectName("lineEditHospitalDestinoSusFacil")
        self.radioButtonOxiSim = QtWidgets.QRadioButton(self.widgetEnfermagem)
        self.radioButtonOxiSim.setGeometry(QtCore.QRect(160, 150, 41, 17))
        self.radioButtonOxiSim.setObjectName("radioButtonOxiSim")
        self.labelHoraEntrSusFacil = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelHoraEntrSusFacil.setGeometry(QtCore.QRect(0, 340, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelHoraEntrSusFacil.setFont(font)
        self.labelHoraEntrSusFacil.setObjectName("labelHoraEntrSusFacil")
        self.labelFC = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelFC.setGeometry(QtCore.QRect(360, 0, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelFC.setFont(font)
        self.labelFC.setObjectName("labelFC")
        self.labelHoraOxiLig = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelHoraOxiLig.setGeometry(QtCore.QRect(200, 150, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelHoraOxiLig.setFont(font)
        self.labelHoraOxiLig.setObjectName("labelHoraOxiLig")
        self.labelHospitalDestinoSusFacil = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelHospitalDestinoSusFacil.setGeometry(QtCore.QRect(190, 370, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.labelHospitalDestinoSusFacil.setFont(font)
        self.labelHospitalDestinoSusFacil.setObjectName("labelHospitalDestinoSusFacil")
        self.textEditDescricaoEnfermagem = QtWidgets.QTextEdit(self.widgetEnfermagem)
        self.textEditDescricaoEnfermagem.setGeometry(QtCore.QRect(0, 30, 641, 111))
        self.textEditDescricaoEnfermagem.setStyleSheet("background-color: rgb(255, 249, 248);")
        self.textEditDescricaoEnfermagem.setObjectName("textEditDescricaoEnfermagem")
        self.lineEditPA2 = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditPA2.setGeometry(QtCore.QRect(490, 0, 151, 20))
        self.lineEditPA2.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditPA2.setObjectName("lineEditPA2")
        self.labelIntercorrencias = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelIntercorrencias.setGeometry(QtCore.QRect(410, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.labelIntercorrencias.setFont(font)
        self.labelIntercorrencias.setObjectName("labelIntercorrencias")
        self.labelPA = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelPA.setGeometry(QtCore.QRect(460, 0, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelPA.setFont(font)
        self.labelPA.setObjectName("labelPA")
        self.lineEditHoraObsFim_2 = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraObsFim_2.setGeometry(QtCore.QRect(590, 370, 51, 20))
        self.lineEditHoraObsFim_2.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraObsFim_2.setObjectName("lineEditHoraObsFim_2")
        self.lineEditHoraObsIni = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraObsIni.setGeometry(QtCore.QRect(480, 310, 61, 20))
        self.lineEditHoraObsIni.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraObsIni.setObjectName("lineEditHoraObsIni")
        self.labelHoraLiberacaoSusFacil = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelHoraLiberacaoSusFacil.setGeometry(QtCore.QRect(0, 370, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.labelHoraLiberacaoSusFacil.setFont(font)
        self.labelHoraLiberacaoSusFacil.setObjectName("labelHoraLiberacaoSusFacil")
        self.labelTemperatura = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelTemperatura.setGeometry(QtCore.QRect(190, 0, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelTemperatura.setFont(font)
        self.labelTemperatura.setObjectName("labelTemperatura")
        self.lineEditHoraIniOxi = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditHoraIniOxi.setGeometry(QtCore.QRect(270, 150, 51, 20))
        self.lineEditHoraIniOxi.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditHoraIniOxi.setObjectName("lineEditHoraIniOxi")
        self.labelMaterialUtilizado = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelMaterialUtilizado.setGeometry(QtCore.QRect(0, 170, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelMaterialUtilizado.setFont(font)
        self.labelMaterialUtilizado.setObjectName("labelMaterialUtilizado")
        self.radioButtonOxiNao = QtWidgets.QRadioButton(self.widgetEnfermagem)
        self.radioButtonOxiNao.setGeometry(QtCore.QRect(110, 150, 41, 20))
        self.radioButtonOxiNao.setObjectName("radioButtonOxiNao")
        self.labelEvolucaoEnfermagem = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelEvolucaoEnfermagem.setGeometry(QtCore.QRect(0, 0, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelEvolucaoEnfermagem.setFont(font)
        self.labelEvolucaoEnfermagem.setObjectName("labelEvolucaoEnfermagem")
        self.labelHoraOxiDeslig = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelHoraOxiDeslig.setGeometry(QtCore.QRect(330, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelHoraOxiDeslig.setFont(font)
        self.labelHoraOxiDeslig.setObjectName("labelHoraOxiDeslig")
        self.label_2 = QtWidgets.QLabel(self.widgetEnfermagem)
        self.label_2.setGeometry(QtCore.QRect(550, 310, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelEvolucaoEnfermagem_2 = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelEvolucaoEnfermagem_2.setGeometry(QtCore.QRect(0, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelEvolucaoEnfermagem_2.setFont(font)
        self.labelEvolucaoEnfermagem_2.setObjectName("labelEvolucaoEnfermagem_2")
        self.labelOxiLPorMin = QtWidgets.QLabel(self.widgetEnfermagem)
        self.labelOxiLPorMin.setGeometry(QtCore.QRect(480, 150, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.labelOxiLPorMin.setFont(font)
        self.labelOxiLPorMin.setObjectName("labelOxiLPorMin")
        self.lineEditFR = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditFR.setGeometry(QtCore.QRect(290, 0, 61, 20))
        self.lineEditFR.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditFR.setObjectName("lineEditFR")
        self.radioButtonIntercorrenciaNeg = QtWidgets.QRadioButton(self.widgetEnfermagem)
        self.radioButtonIntercorrenciaNeg.setGeometry(QtCore.QRect(490, 370, 41, 17))
        self.radioButtonIntercorrenciaNeg.setObjectName("radioButtonIntercorrenciaNeg")
        self.lineEditFC = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditFC.setGeometry(QtCore.QRect(390, 0, 61, 20))
        self.lineEditFC.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditFC.setObjectName("lineEditFC")
        self.lineEditTemperatura = QtWidgets.QLineEdit(self.widgetEnfermagem)
        self.lineEditTemperatura.setGeometry(QtCore.QRect(220, 0, 41, 20))
        self.lineEditTemperatura.setStyleSheet("background-color: rgb(242, 255, 250);")
        self.lineEditTemperatura.setObjectName("lineEditTemperatura")
        FichaAmbulatorial.setCentralWidget(self.centralwidget)

        self.retranslateUi(FichaAmbulatorial)
        QtCore.QMetaObject.connectSlotsByName(FichaAmbulatorial)

    def retranslateUi(self, FichaAmbulatorial):
        _translate = QtCore.QCoreApplication.translate
        FichaAmbulatorial.setWindowTitle(_translate("FichaAmbulatorial", "Ficha Ambulatorial"))
        self.labelTitulo.setText(_translate("FichaAmbulatorial", "ASSOCIAÇÃO PREFEITO HÉLCIO VALENTIM DE ANDRADE"))
        self.labelSubTitulo.setText(_translate("FichaAmbulatorial", "Rua Lajão, 93 – Centro – Conselheiro Pena/MG - Telefone: (33) 3261-3115"))
        self.labelCorRaca.setText(_translate("FichaAmbulatorial", "Cor/Raça:"))
        self.labelNomeMae.setText(_translate("FichaAmbulatorial", "Nome da Mãe:"))
        self.labelTelefone2.setText(_translate("FichaAmbulatorial", "Tel:"))
        self.labelAssinatura.setText(_translate("FichaAmbulatorial", "Assinatura do Responsável:"))
        self.labelCidade.setText(_translate("FichaAmbulatorial", "Cidade: "))
        self.label_3.setText(_translate("FichaAmbulatorial", "Endereço:"))
        self.labelBairro.setText(_translate("FichaAmbulatorial", "Bairro:"))
        self.radioButton_3.setText(_translate("FichaAmbulatorial", "Convênio"))
        self.labelNome.setText(_translate("FichaAmbulatorial", "Nome:"))
        self.labelDataNasc.setText(_translate("FichaAmbulatorial", "Data Nasc:"))
        self.radioButton.setText(_translate("FichaAmbulatorial", "SUS"))
        self.label.setText(_translate("FichaAmbulatorial", "Horário: "))
        self.labelTema.setText(_translate("FichaAmbulatorial", "FICHA DE ATENDIMENTO AMBULATORIAL"))
        self.labelNumero.setText(_translate("FichaAmbulatorial", "Nº:"))
        self.labelData.setText(_translate("FichaAmbulatorial", "Data:"))
        self.labelIdade.setText(_translate("FichaAmbulatorial", "Idade:"))
        self.labelTelefone1.setText(_translate("FichaAmbulatorial", "Tel:"))
        self.radioButton_2.setText(_translate("FichaAmbulatorial", "Particular"))
        self.labelSexo.setText(_translate("FichaAmbulatorial", "Sexo: "))
        self.labelCns.setText(_translate("FichaAmbulatorial", "Nº Cartão Nacional SUS: "))
        self.labelDiagnsticoMedico.setText(_translate("FichaAmbulatorial", "DIAGNÓSTICO PRINCIPAL"))
        self.labelProcedimentoMedico.setText(_translate("FichaAmbulatorial", "PROCEDIMENTO:"))
        self.labelTema_2.setText(_translate("FichaAmbulatorial", "INFORMAÇÕES DO ATENDIMENTO REALIZADO"))
        self.labelIdentificascaoMedico.setText(_translate("FichaAmbulatorial", "IDENTIFICAÇÃO DO PROFISSIONAL MÉDICO:"))
        self.labelObsMedicaNaUnidade.setText(_translate("FichaAmbulatorial", "OBSERVAÇÃO MÉDICA NA UNIDADE (Justificar indicação e informar n° de horas) horário:"))
        self.radioButtonIntercorrenciaNeg_2.setText(_translate("FichaAmbulatorial", "Sim"))
        self.labelFR.setText(_translate("FichaAmbulatorial", "FR:"))
        self.radioButtonOxiSim.setText(_translate("FichaAmbulatorial", "Sim"))
        self.labelHoraEntrSusFacil.setText(_translate("FichaAmbulatorial", "TRANSFERÊNCIA: Horário entrada SUS fácil:"))
        self.labelFC.setText(_translate("FichaAmbulatorial", "FC:"))
        self.labelHoraOxiLig.setText(_translate("FichaAmbulatorial", "Ligado às :"))
        self.labelHospitalDestinoSusFacil.setText(_translate("FichaAmbulatorial", "Hospital: "))
        self.labelIntercorrencias.setText(_translate("FichaAmbulatorial", "Intercorrência:"))
        self.labelPA.setText(_translate("FichaAmbulatorial", "PA:"))
        self.labelHoraLiberacaoSusFacil.setText(_translate("FichaAmbulatorial", "Horário liberação: "))
        self.labelTemperatura.setText(_translate("FichaAmbulatorial", "TAX:"))
        self.labelMaterialUtilizado.setText(_translate("FichaAmbulatorial", "MATERIAL UTILIZADO"))
        self.radioButtonOxiNao.setText(_translate("FichaAmbulatorial", "Não"))
        self.labelEvolucaoEnfermagem.setText(_translate("FichaAmbulatorial", "EVOLUÇÃO DE ENFERMAGEM:"))
        self.labelHoraOxiDeslig.setText(_translate("FichaAmbulatorial", "Desligado às:"))
        self.label_2.setText(_translate("FichaAmbulatorial", "às"))
        self.labelEvolucaoEnfermagem_2.setText(_translate("FichaAmbulatorial", "UTILIZAÇÃO O²:"))
        self.labelOxiLPorMin.setText(_translate("FichaAmbulatorial", "L. Por min:"))
        self.radioButtonIntercorrenciaNeg.setText(_translate("FichaAmbulatorial", "Não"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FichaAmbulatorial = QtWidgets.QMainWindow()
    ui = Ui_FichaAmbulatorial()
    ui.setupUi(FichaAmbulatorial)
    FichaAmbulatorial.show()
    sys.exit(app.exec_())
